### ISSUE TITLE
Zigbee Protocol Support

### ISSUE THREAD

**Issue by bryanbr23** [Azure/iot-plug-and-play-bridge#37]
While popular in the home automation space, Zigbee remains a popular wireless protocol.  
Are there plans to support ZigBee protocols and/or Discovery of Zigbee gateways or endpoint devices?  

Thanks,
  ~Bryan

**Comment by usivagna** [comment]
Thanks for filing feedback! While we currently do not have any plans to support Zigbee, we're actively seeking feedback on the next adapters we should build. 

I will keep this issue open to track this request and update the thread if/when our plans change on Zigbee. If you have specific scenarios/customers in mind for Zigbee, feel free to comment them here.

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
