### ISSUE TITLE
BLE for Linux

### ISSUE THREAD

**Issue by oliverchristen** [Azure/iot-plug-and-play-bridge#38]
I'm looking forward to have the PnP bridge available as a Azure IoT Edge module as already planned. But it would really useful to have the BLE bridge available for linux as it is a very popular scenario, don't you think too? Is there a specific reason why it's not yet planned to support it?

**Comment by usivagna** [comment]
Thanks for the feedback @oliverchristen ! During our Public Preview, we did not have any specific requests to support a BLE adapter on Linux. However, we have started to get more requests on supporting this scenario. I've started discussions with the team to consider adding this to our plan. I'll update this thread when we have more to share. 

Thanks!
Ugan

**Comment by usivagna** [comment]
Given current resourcing, this won't be immediately be addressed by the bridge team. In the meantime, if anyone in the community would like to add Linux support to the [BLE Adapter,](https://aka.ms/iot-pnp-bridge-bluetooth) we welcome [contributions](https://github.com/Azure/iot-plug-and-play-bridge/blob/master/CONTRIBUTING.md)!

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
