### ISSUE TITLE
NO_LOGGING = ON flag in build.sh script not structured

### ISSUE THREAD

**Issue by eddylawsurgere** [Azure/iot-plug-and-play-bridge#59]
**Describe the bug**
When I set the flag "no_logging=ON" in build.sh and I run it, I got the error, see screenshot below.

error in log:
/usr/bin/ld: CMakeFiles/pnpbridge_bin.dir/main.c.o: in function `main':
main.c:(.text+0x43): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: main.c:(.text+0xe6): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: main.c:(.text+0x169): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: ../../libpnpbridge.a(pnpbridge.c.o): in function `PnpBridge_InitializePnpDeviceConfig':
pnpbridge.c:(.text+0x191): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: pnpbridge.c:(.text+0x286): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: ../../libpnpbridge.a(pnpbridge.c.o):pnpbridge.c:(.text+0x37b): more undefined references to `xlogging_get_log_function' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/pnpbridge/samples/console/CMakeFiles/pnpbridge_bin.dir/build.make:125: src/pnpbridge/samples/console/pnpbridge_bin] Error 1
make[1]: *** [CMakeFiles/Makefile2:2483: src/pnpbridge/samples/console/CMakeFiles/pnpbridge_bin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/pnpbridge_module.dir/main.c.o: in function `main':
main.c:(.text+0xd): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: CMakeFiles/pnpbridge_module.dir/__/src/configuration_parser.c.o: in function `PnpBridgeConfig_GetConnectionDetails':
configuration_parser.c:(.text+0x4c): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: configuration_parser.c:(.text+0xc3): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: configuration_parser.c:(.text+0x1a7): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: configuration_parser.c:(.text+0x20e): undefined reference to `xlogging_get_log_function'
/usr/bin/ld: CMakeFiles/pnpbridge_module.dir/__/src/configuration_parser.c.o:configuration_parser.c:(.text+0x297): more undefined references to `xlogging_get_log_function' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/pnpbridge/module/CMakeFiles/pnpbridge_module.dir/build.make:262: src/pnpbridge/module/pnpbridge_module] Error 1
make[1]: *** [CMakeFiles/Makefile2:2532: src/pnpbridge/module/CMakeFiles/pnpbridge_module.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Screenshots**
![image](https://user-images.githubusercontent.com/75318786/115439220-54a66480-a1dc-11eb-8655-e34d63119c9e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by usivagna** [comment]
Thanks Eddy for filing the issue, @dipannita08  can you have a look into this?

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
