### ISSUE TITLE
[Question] - How to use the single DeviceId from IotHub perspective for multiple devices reporting different telemetry

### ISSUE THREAD

**Issue by pesetskyps** [Azure/iot-plug-and-play-bridge#61]
- Do I understand correctly that at this phase the bridge can is made to report only telemetry for single device as it is deporting to single Device Id from IotHub perspective. Is it correct?
- Is there any plan to support multiple device reporting telemetry through it and have mapping of telemetry to specific device Id in IotHub?

Thank you for your work guys, looks promising! This could be good enabler of mass migration for existing device that cannot be rewritten to support Azure Iot. Keep it up

**Comment by usivagna** [comment]
Thank you for the question Pavel! You are correct in that currently that an instance of the bridge only reports telemetry through a single Device ID (or module ID when running as an IoT Edge runtime module). Right now if you want multiple IDs you can run multiple instances of the bridge on the gateway/device. 

We have plans in the backlog to enable routing to multiple device ids from a single instance of the bridge however there is no firm date yet on when our team plans to implement this. 

In the meantime we encourage contributions to the community, and anyone who would like to add/propose support for this by modifying our open source is welcome to do so via a PR or issue! 👍

**Comment by dberenguer** [comment]
But is the Azure device SDK ready to transmit messages to the IoT HUB on behalf of other devices via AMQP? Otherwise this modification might not be possible without changing the SDK AMQP layer.

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
