### ISSUE TITLE
[Question] why build the releases in debug mode ?

### ISSUE THREAD

**Issue by michelkamp** [Azure/iot-plug-and-play-bridge#64]
Enter your question here:
I was wondering if you could also provide a release build of the bridge ? Since now it looks like a debug build so i will have to install VS C++ , since else it will miss the VCRUNTIME140**D**.dll

please correct me if i am wrong. 
michel

**Comment by usivagna** [comment]
@dipannita08 can we provide an additional build on our release page?

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
