### ISSUE TITLE
404 on https://github.com/Azure/iot-plug-and-play-bridge/tree/master/serialpnp/STM32Example  and where is az iot pnp?

### ISSUE THREAD

**Issue by djaus2** [Azure/iot-plug-and-play-bridge#73]
**Describe the bug**
The link to setup az iot pnp is a 404

**To Reproduce**
1. Go to https://github.com/Azure/iot-plug-and-play-bridge/tree/master/serialpnp/STM32Example
2. Click on instruction in the line:  **Follow the instruction here to setup Azure Pnp CLI**  _(Nb should be instructions)_
3. You get a a 404

**Expected behavior**
Get those instructions :(

**Additional context**
Ps: How do you run ```az iot pnp``` anyway??
There is no ```az iot pnp``` at https://docs.microsoft.com/en-us/cli/azure/iot?view=azure-cli-latest

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo is planned to be **archived as a read-only repository on November 30th 2023**. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
