### ISSUE TITLE
[BUG]DPS with IoT Central supported? 

### ISSUE THREAD

**Issue by KijoKim76** [Azure/iot-plug-and-play-bridge#79]
**Describe the bug**
Tried DPS but failed with unauthorized. Looks this code doesn't include changes in IoT Central side. 

**To Reproduce**
1. Create device
2. Set dps and other configuration
3. Run 

**Expected behavior**
DPS succeed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, or Windows (Version 2004)]
 - Copy of the config.json file
 - Copy of PnP interface json

**Additional context**

**Comment by KijoKim76** [comment]
0x0000029bbe136860 "{\"errorCode\":401000,\"trackingId\":\"d0035b49-4e00-4744-963f-e758bf4bd74a\",\"message\":\"Unauthorized\",\"timestampUtc\":\"2022-06-14T07:07:13.1412244Z\"}"

**Comment by usivagna** [comment]
Thank you for your interest in the IoT Plug and Play bridge, unfortunately due to new innovations in Azure IoT and changes in product strategy we have come to the decision to deprecate the IoT Plug and Play bridge. Thank you to the community for your support on this journey. The repo will be marked as read-only repository on November 30th 2023. Thank you to everyone who contributed bug fixes and new adapters for connecting devices with IoT Plug and Play. You can find the latest IoT innovations at [https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog](https://techcommunity.microsoft.com/t5/internet-of-things-blog/bg-p/IoTBlog). Please note that any use of archived repositories introduces more risks from a security standpoint and should be done with caution.
